const KEY='controlAsientos_v4';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const blank=()=>Array.from({length:50},(_,i)=>({id:i+1,status:'vacant',passenger:'',phone:'',origin:'',destination:'',ticket:'',fare:0,deposit:0}));
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{capacity:50,date:new Date().toISOString().slice(0,10),scale:100,view:'layout',filter:'all',format:'png',trip:{route:'Ruta Principal - Destino Directo',time:'08:00',driver:'Conductor Designado',plate:'BUS-50'},seats:blank()};
state.seats=(state.seats||blank()).map((s,i)=>({...blank()[i],...s,fare:Number(s.fare)||0,deposit:Number(s.deposit)||0}));let selected=null;const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);const balanceOf=s=>Math.max(0,(Number(s.fare)||0)-(Number(s.deposit)||0));const labels={vacant:'Vacante',reserved:'Apartado',paid:'Pagado',absent:'Ausente'};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function stats(){let a=state.seats.slice(0,state.capacity),occupied=a.filter(s=>s.status!='vacant').length,paid=a.filter(s=>s.status=='paid').length;const totalFare=a.reduce((t,s)=>t+(Number(s.fare)||0),0),totalDeposit=a.reduce((t,s)=>t+(Number(s.deposit)||0),0),totalBalance=Math.max(0,totalFare-totalDeposit);return{occupied,paid,vacant:state.capacity-occupied,percent:Math.round(occupied/state.capacity*100),reserved:a.filter(s=>s.status=='reserved').length,totalFare,totalDeposit,totalBalance}}
function seatButton(s){return `<button class="seat ${s.status}" data-seat="${s.id}"><b>#${s.id}</b><span>${s.passenger||labels[s.status]}${s.passenger?`<small style="display:block;margin-top:4px;color:${balanceOf(s)>0?'#fbbf24':'#34d399'}">${balanceOf(s)>0?'Debe '+money(balanceOf(s)):'Liquidado'}</small>`:''}</span></button>`}
function renderBus(){let rows='';for(let r=0;r<11;r++){let ids=[r*4+1,r*4+2,null,r*4+3,r*4+4];rows+=ids.map(id=>id?seatButton(state.seats[id-1]):`<div class="rownum">${r+1}</div>`).join('')}let extra='';if(state.capacity>=45)extra+=seatButton(state.seats[44]);if(state.capacity>=46)extra+=seatButton(state.seats[45]);extra+=`<div class="rownum">12</div><div class="wc">ESCALERA / WC</div>`;let rear=[47,48,49,50].filter(n=>n<=state.capacity).map(n=>seatButton(state.seats[n-1])).join('');$('#bus').innerHTML=`<div class="busHead"><div class="busTitle"><div><b>🚌 AUTOBÚS ${state.capacity} PASAJEROS</b><small style="display:block;color:#3191ff">${state.trip.route}</small></div><div style="text-align:right"><span class="tag">▣ ${state.date}</span><small style="display:block">Placas: <b>${state.trip.plate}</b></small></div></div><div class="driverRow"><div class="info"><small>CONDUCTOR</small><br><b>${state.trip.driver}</b></div><div class="info" style="text-align:right"><small style="color:#1de0ad">ACCESO</small><br><b>Puerta Delantera</b></div></div><div class="front">──── FRENTE DEL AUTOBÚS ────</div></div><div class="seatgrid">${rows}${extra}</div><div class="rearLabel">FONDO DEL AUTOBÚS · F13</div><div class="rear">${rear}</div><div class="rearFoot">••• PARTE TRASERA · ${state.capacity} ASIENTOS •••<small style="display:block;margin-top:8px">Generado el ${state.date.split('-').reverse().join('/')} · Sistema Control de Asientos</small></div>`;$('#bus').style.transform=`scale(${state.scale/100})`}
function renderList(){let q=$('#search').value.toLowerCase();let arr=state.seats.slice(0,state.capacity).filter(s=>{let match=!q||('#'+s.id+' '+s.passenger+' '+s.ticket+' '+s.destination).toLowerCase().includes(q);let f=state.filter=='all'||state.filter=='vacant'&&s.status=='vacant'||state.filter=='paid'&&s.status=='paid'||state.filter=='occupied'&&s.status!='vacant';return match&&f});$('#seatList').innerHTML=arr.map(s=>`<button class="seatCard ${s.status}" data-seat="${s.id}"><span class="num">#${s.id}</span><span class="copy"><b>${s.passenger||labels[s.status]}</b><small>${s.passenger?(s.destination||'Sin destino'):'Toca para asignar pasajero'}</small>${s.passenger?`<span class="moneyLine"><b class="due">Cobro ${money(s.fare)}</b><b class="paidMoney">Abono ${money(s.deposit)}</b><b class="debt">Saldo ${money(balanceOf(s))}</b></span>`:''}</span><span class="chair">▱</span></button>`).join('')}
function render(){let st=stats();$('#date').value=state.date;$('#capTag').textContent=state.capacity+' Pasajeros';$('#tripLine').textContent=`${state.trip.route} · ${state.trip.time}`;$('#stats').innerHTML=`<div class="statsWrap"><span class="pill"><i></i>Vacíos: <b>${st.vacant}</b></span><span class="pill"><i style="background:#3989ff"></i>Ocupados: <b>${st.occupied}</b></span><span class="pill"><i style="background:#1de0ad"></i>Abordados: <b>${st.paid}</b></span><span class="pill"><i style="background:#b978ff"></i>Ocupación: <b>${st.percent}%</b></span></div>`;$('#listCount').textContent=st.occupied;$('#scaleLabel').textContent=state.scale+'%';$$('#caps button').forEach(b=>b.classList.toggle('on',+b.dataset.cap==state.capacity));$('#layoutView').hidden=state.view!='layout';$('#listView').hidden=state.view!='list';$('#layoutBtn').classList.toggle('on',state.view=='layout');$('#listBtn').classList.toggle('on',state.view=='list');renderBus();renderList();save()}
function openSeat(id){selected=state.seats[id-1];$('#seatTitle').textContent='Asiento #'+id;['passenger','phone','origin','destination','ticket'].forEach(k=>$('#'+k).value=selected[k]||'');$('#fare').value=selected.fare||'';$('#deposit').value=selected.deposit||'';updateBalanceField();$('#status').value=selected.status=='vacant'?'reserved':selected.status;$('#freeSeat').style.display=selected.status=='vacant'?'none':'';$('#seatModal').hidden=false}
document.addEventListener('click',e=>{let s=e.target.closest('[data-seat]');if(s)openSeat(+s.dataset.seat);let c=e.target.closest('[data-close]');if(c)$('#'+c.dataset.close).hidden=true});
function updateBalanceField(){const fare=Math.max(0,Number($('#fare').value)||0),deposit=Math.max(0,Number($('#deposit').value)||0);$('#balance').value=money(Math.max(0,fare-deposit));}$('#fare').oninput=updateBalanceField;$('#deposit').oninput=updateBalanceField;
$('#saveSeat').onclick=()=>{let p=$('#passenger').value.trim();if(!p)return toast('Captura el nombre del pasajero');Object.assign(selected,{passenger:p,phone:$('#phone').value,origin:$('#origin').value,destination:$('#destination').value,ticket:$('#ticket').value,fare:Math.max(0,Number($('#fare').value)||0),deposit:Math.max(0,Number($('#deposit').value)||0),status:$('#status').value});$('#seatModal').hidden=true;render();toast('Asiento guardado')};$('#freeSeat').onclick=()=>{Object.assign(selected,{status:'vacant',passenger:'',phone:'',origin:'',destination:'',ticket:'',fare:0,deposit:0});$('#seatModal').hidden=true;render();toast('Asiento liberado')};
$$('#caps button').forEach(b=>b.onclick=()=>{state.capacity=+b.dataset.cap;state.trip.plate='BUS-'+state.capacity;render()});$('#date').onchange=e=>{state.date=e.target.value;render()};$('#layoutBtn').onclick=()=>{state.view='layout';render()};$('#listBtn').onclick=()=>{state.view='list';render()};$('#zoomOut').onclick=()=>{state.scale=Math.max(70,state.scale-10);render()};$('#zoomIn').onclick=()=>{state.scale=Math.min(130,state.scale+10);render()};$('#zoomReset').onclick=()=>{state.scale=100;render()};$('#search').oninput=renderList;$$('#filters button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('on',x==b));renderList()});
$('#tripBtn').onclick=()=>{Object.entries(state.trip).forEach(([k,v])=>$('#'+k).value=v);$('#tripModal').hidden=false};$('#saveTrip').onclick=()=>{['route','time','driver','plate'].forEach(k=>state.trip[k]=$('#'+k).value);$('#tripModal').hidden=true;render();toast('Viaje actualizado')};
function reportText(){let st=stats(),p=state.seats.slice(0,state.capacity).filter(s=>s.status!='vacant');return `*REPORTE DE VIAJE Y COBRANZA*\n${state.trip.route}\nFecha: ${state.date}\nSalida: ${state.trip.time}\nConductor: ${state.trip.driver}\nUnidad: ${state.trip.plate}\nOcupación: ${st.occupied}/${state.capacity} (${st.percent}%)\n\n*RESUMEN DE COBRANZA*\nTotal a cobrar: ${money(st.totalFare)}\nTotal abonado: ${money(st.totalDeposit)}\nSaldo pendiente: ${money(st.totalBalance)}\n\n*PASAJEROS*\n${p.length?p.map(s=>`#${s.id} ${s.passenger} · ${labels[s.status]} · Cobro ${money(s.fare)} · Abono ${money(s.deposit)} · Saldo ${money(balanceOf(s))}${s.destination?' · '+s.destination:''}`).join('\n'):'Sin pasajeros asignados.'}`}
function renderReport(){let st=stats(),p=state.seats.slice(0,state.capacity).filter(s=>s.status!='vacant');$('#reportPreview').innerHTML=`<div class="reportCard" id="capture"><div class="reportTitle"><div><span class="tag">REPORTE DE VIAJE, MANIFIESTO Y COBRANZA</span><h2>${state.trip.route}</h2></div><div><small>Autobús / Placa</small><b style="display:block;color:#1de0ad">${state.trip.plate}</b></div></div><div class="tripfacts"><div><small>FECHA</small><b>${state.date}</b></div><div><small>HORA SALIDA</small><b>${state.trip.time}</b></div><div><small>CONDUCTOR</small><b>${state.trip.driver}</b></div><div><small>CAPACIDAD</small><b>${state.capacity} Asientos</b></div></div><p><b>Ocupación del Autobús</b><b style="float:right;color:#1de0ad">${st.occupied}/${state.capacity} (${st.percent}%)</b></p><div class="progress"><div style="width:${st.percent}%"></div></div><div class="summary"><div><small>Ocupados</small><b>${st.occupied}</b></div><div><small>Libres</small><b style="color:#1de0ad">${st.vacant}</b></div><div><small>Pagados</small><b style="color:#1de0ad">${st.paid}</b></div><div><small>Apartados</small><b style="color:#ffd21a">${st.reserved}</b></div></div><div class="financialSummary"><div><small>TOTAL A COBRAR</small><b style="color:#60a5fa">${money(st.totalFare)}</b></div><div><small>TOTAL ABONADO</small><b style="color:#34d399">${money(st.totalDeposit)}</b></div><div><small>SALDO PENDIENTE</small><b style="color:#f87171">${money(st.totalBalance)}</b></div></div><div class="manifest"><small>DETALLE POR PASAJERO / ASIENTO (${p.length})</small>${p.length?`<div style="overflow:auto"><table class="financeTable"><thead><tr><th>Asiento</th><th>Pasajero</th><th>Estado</th><th class="right">Cobro</th><th class="right">Abono</th><th class="right">Saldo</th></tr></thead><tbody>${p.map(s=>`<tr><td>#${s.id}</td><td>${s.passenger}</td><td>${labels[s.status]}</td><td class="right">${money(s.fare)}</td><td class="right">${money(s.deposit)}</td><td class="right" style="color:${balanceOf(s)>0?'#f87171':'#34d399'}">${money(balanceOf(s))}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sin pasajeros asignados aún en este viaje.</div>'}</div></div>`}
$('#reportBtn').onclick=()=>{renderReport();$('#reportModal').hidden=false};$$('[data-format]').forEach(b=>b.onclick=()=>{state.format=b.dataset.format;$$('[data-format]').forEach(x=>x.classList.toggle('on',x==b));$('#downloadImage').textContent='⇩ Descargar Imagen ('+state.format.toUpperCase()+')';save()});
async function captureBlob(){let node=$('#capture'),clone=node.cloneNode(true),w=node.scrollWidth,h=node.scrollHeight;let css=[...document.styleSheets].map(s=>{try{return [...s.cssRules].map(r=>r.cssText).join('')}catch{return''}}).join('');let xml=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml"><style>${css}</style>${clone.outerHTML}</div></foreignObject></svg>`;let svg=new Blob([xml],{type:'image/svg+xml'}),url=URL.createObjectURL(svg),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});let c=document.createElement('canvas');c.width=w*2;c.height=h*2;let x=c.getContext('2d');x.scale(2,2);x.drawImage(img,0,0);URL.revokeObjectURL(url);return await new Promise(res=>c.toBlob(res,state.format=='jpg'?'image/jpeg':'image/png',.92))}

function pdfEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,c=>{const map={'á':'a','é':'e','í':'i','ó':'o','ú':'u','Á':'A','É':'E','Í':'I','Ó':'O','Ú':'U','ñ':'n','Ñ':'N','ü':'u','Ü':'U','•':'-'};return map[c]||'?'});}
function wrapPdf(text,max=88){const out=[];String(text).split('\n').forEach(line=>{if(!line){out.push('');return}let words=line.split(/\s+/),cur='';words.forEach(w=>{if((cur+' '+w).trim().length>max){out.push(cur);cur=w}else cur=(cur+' '+w).trim()});out.push(cur)});return out;}
function createPdfBlob(){
  const st=stats(), passengers=state.seats.slice(0,state.capacity).filter(s=>s.status!='vacant');
  const lines=[
    'REPORTE DE VIAJE Y MANIFIESTO','',state.trip.route,
    `Fecha: ${state.date}    Hora de salida: ${state.trip.time}`,
    `Conductor: ${state.trip.driver}`,
    `Autobus / Placa: ${state.trip.plate}    Capacidad: ${state.capacity} asientos`,
    `Ocupacion: ${st.occupied}/${state.capacity} (${st.percent}%)    Libres: ${st.vacant}    Pagados: ${st.paid}    Apartados: ${st.reserved}`,
    '', 'RESUMEN DE COBRANZA',
    `Total a cobrar: ${money(st.totalFare)}    Total abonado: ${money(st.totalDeposit)}    Saldo pendiente: ${money(st.totalBalance)}`,
    '','DETALLE POR PASAJERO / ASIENTO'
  ];
  if(!passengers.length) lines.push('Sin pasajeros asignados en este viaje.');
  passengers.forEach(s=>lines.push(`#${s.id} ${s.passenger} | ${labels[s.status]} | Cobro ${money(s.fare)} | Abono ${money(s.deposit)} | Saldo ${money(balanceOf(s))} | ${s.origin||'Sin origen'} - ${s.destination||'Sin destino'}${s.phone?' | Tel: '+s.phone:''}${s.ticket?' | Boleto: '+s.ticket:''}`));
  lines.push('','Generado por Control de Asientos de Autobus');
  const wrapped=wrapPdf(lines.join('\n'));
  const pages=[]; for(let i=0;i<wrapped.length;i+=48) pages.push(wrapped.slice(i,i+48));
  const objects=[]; const add=s=>(objects.push(s),objects.length);
  const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const pageIds=[];
  const contentIds=[];
  pages.forEach((page,pi)=>{
    let y=760, cmds=['BT','/F1 10 Tf'];
    page.forEach((line,li)=>{const size=(pi===0&&li===0)?16:10;cmds.push(`/${'F1'} ${size} Tf 50 ${y} Td (${pdfEscape(line)}) Tj ${-50} ${-(y-14)} Td`);y-=14});
    cmds.push('ET'); const stream=cmds.join('\n');
    contentIds.push(add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`));
    pageIds.push(add('PENDING'));
  });
  const pagesId=objects.length+1; objects.push('PAGES_PENDING');
  pageIds.forEach((id,i)=>objects[id-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);
  objects[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${pageIds.length} >>`;
  const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
  let pdf='%PDF-1.4\n', offsets=[0]; objects.forEach((o,i)=>{offsets[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});
  const xref=pdf.length; pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`; for(let i=1;i<=objects.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';
  pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([pdf],{type:'application/pdf'});
}
function pdfFile(){return new File([createPdfBlob()],`reporte-asientos-${state.date}.pdf`,{type:'application/pdf'});}
function downloadPdf(){const f=pdfFile(),a=document.createElement('a');a.href=URL.createObjectURL(f);a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Reporte PDF descargado');}
async function sharePdf(){const f=pdfFile();if(navigator.share&&navigator.canShare?.({files:[f]})){try{await navigator.share({title:'Reporte de viaje',text:reportText(),files:[f]})}catch(e){if(e.name!='AbortError')toast('No fue posible compartir el PDF')}}else{downloadPdf();toast('PDF descargado. Adjuntalo en WhatsApp o correo.')}}
$('#downloadPdf').onclick=downloadPdf;
$('#sharePdf').onclick=sharePdf;
$('#whatsappPdf').onclick=async()=>{const f=pdfFile();if(navigator.share&&navigator.canShare?.({files:[f]})){try{await navigator.share({title:'Reporte para WhatsApp',text:reportText(),files:[f]})}catch(e){if(e.name!='AbortError')toast('No fue posible compartir')}}else{downloadPdf();window.open('https://wa.me/?text='+encodeURIComponent(reportText()+'\n\nEl reporte PDF fue descargado. Adjuntalo en este chat.'),'_blank')}};
$('#emailPdf').onclick=async()=>{const f=pdfFile();if(navigator.share&&navigator.canShare?.({files:[f]})){try{await navigator.share({title:'Reporte de viaje',text:reportText(),files:[f]});return}catch(e){if(e.name=='AbortError')return}}downloadPdf();const subject=encodeURIComponent('Reporte de viaje - '+state.trip.route+' - '+state.date),body=encodeURIComponent(reportText()+'\n\nAdjunto manualmente el reporte PDF descargado.');window.location.href=`mailto:?subject=${subject}&body=${body}`;};

$('#downloadImage').onclick=async()=>{try{let b=await captureBlob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`reporte-asientos-${state.date}.${state.format}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Imagen descargada')}catch{toast('No fue posible generar la imagen')}};$('#copyImage').onclick=async()=>{try{let b=await captureBlob();await navigator.clipboard.write([new ClipboardItem({'image/png':b})]);toast('Imagen copiada')}catch{toast('El navegador no permite copiar esta imagen')}};$('#shareText').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(reportText()),'_blank');$('#shareImage').onclick=async()=>{try{let b=await captureBlob(),f=new File([b],`reporte.${state.format}`,{type:b.type});if(navigator.share&&navigator.canShare?.({files:[f]}))await navigator.share({title:'Reporte de viaje',text:reportText(),files:[f]});else window.open('https://wa.me/?text='+encodeURIComponent(reportText()),'_blank')}catch(e){if(e.name!='AbortError')toast('No fue posible compartir')}};
function downloadJSON(){let a=document.createElement('a'),b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download=`respaldo-asientos-${state.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('#backupBtn').onclick=downloadJSON;$$('[data-rtab]').forEach(b=>b.onclick=()=>{if(b.dataset.rtab=='json')downloadJSON();$$('[data-rtab]').forEach(x=>x.classList.toggle('on',x==b))});
$('#restoreBtn').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d||!Array.isArray(d.seats)||!d.trip)throw new Error('Formato incorrecto');state=d;save();render();toast('Respaldo restaurado correctamente')}catch(err){toast('El archivo no es un respaldo válido')}finally{e.target.value=''}};
if(location.protocol!=='file:'&&'serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();